=== rkproject24/virtual-classroom/tags/8Jan2012/WebContent/WEB-INF/conf/jchatboxresources.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- jChaBox resource DTD - JavaZOOM -->
<!ELEMENT resources (element*)>
<!--Resource's element-->
<!ELEMENT element (name, value)>
<!--Resource's name-->
<!ELEMENT name (#PCDATA)>
<!--Resource's value-->
<!ELEMENT value (#PCDATA)>

=== rkproject24/virtual-classroom/WebContent/WEB-INF/conf/resources_es.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE resources SYSTEM "jchatboxresources.dtd"> -->
<resources>
    <!-- Resources matching to login.jsp -->
    <element>
        <name>login.date.format</name>
        <value>dd/MM/yyyy HH:mm</value>
    </element>
    <element>
        <name>login.title</name>
        <value>Entra al Chat</value>
    </element>
    <element>
        <name>login.username.label</name>
        <value>Usuario : </value>
    </element>
    <element>
        <name>login.join.link</name>
        <value>Entrar</value>
    </element>
    <element>
        <name>login.join.label</name>
        <value> sala de chat : </value>
    </element>
    <element>
        <name>login.list.label</name>
        <value>Selecciona sala de chat</value>
    </element>
    <element>
        <name>login.chatroom.label</name>
        <value>Sala de Chat : </value>
    </element>
    <element>
        <name>login.open.label</name>
        <value>Abierta : </value>
    </element>
    <element>
        <name>login.subject.label</name>
        <value>Tema : </value>
    </element>
    <element>
        <name>login.useramount.label</name>
        <value>Usuarios : </value>
    </element>
    <element>
        <name>login.userlimit.label</name>
        <value>Máximo de usuarios : </value>
    </element>
    <element>
        <name>login.chatroomnotfound.error</name>
        <value>NO SE ENCONTRO SALA DE CHAT.</value>
    </element>
    <element>
        <name>login.closed.error</name>
        <value>SALA DE CHAT CERRADA.</value>
    </element>
    <element>
        <name>login.novacancies.error</name>
        <value>SALA DE CHAT LLENA.</value>
    </element>
    <element>
        <name>login.namenotavailable.error</name>
        <value>NOMBRE DE USUARIO NO DISPONIBLE.</value>
    </element>
    <element>
        <name>login.banned.error</name>
        <value>TU ACCESO ESTA RESTRINGIDO.</value>
    </element>
    <!-- Resources matching to chatroom.jsp -->
    <element>
        <name>chatroom.date.format</name>
        <value>dd/MM/yyyy HH:mm</value>
    </element>
    <element>
        <name>chatroom.title</name>
        <value>Sala de chat</value>
    </element>
    <element>
        <name>chatroom.join.label</name>
        <value> ha entrado a la sala de chat.</value>
    </element>
    <element>
        <name>chatroom.quit.label</name>
        <value> ha salido de la sala de chat.</value>
    </element>
    <element>
        <name>chatroom.userlist.label</name>
        <value>Usuarios : </value>
    </element>
    <!-- Resources matching to text.jsp -->
    <element>
        <name>board.date.format</name>
        <value>dd/MM/yyyy HH:mm</value>
    </element>
    <element>
        <name>board.title</name>
        <value>Chat</value>
    </element>
    <element>
        <name>board.chatroom.label</name>
        <value>Sala de chat : </value>
    </element>
    <element>
        <name>board.date.label</name>
        <value>Abierta : </value>
    </element>
    <element>
        <name>board.subject.label</name>
        <value>Tema : </value>
    </element>
    <element>
        <name>board.message.label</name>
        <value>Mensaje : </value>
    </element>
    <element>
        <name>board.send.link</name>
        <value>Enviar</value>
    </element>
    <element>
        <name>board.send.label</name>
        <value> a Todos los Usuarios</value>
    </element>
    <element>
        <name>board.refresh.link</name>
        <value>actualizar</value>
    </element>
    <element>
        <name>board.logout.link</name>
        <value>salir</value>
    </element>
    <!-- Resources matching to private.jsp -->
    <element>
        <name>privateboard.date.format</name>
        <value>dd/MM/yyyy</value>
    </element>
    <element>
        <name>privateboard.title</name>
        <value>Mensaje Privado</value>
    </element>
    <element>
        <name>privateboard.chatroom.label</name>
        <value>Sala de chat : </value>
    </element>
    <element>
        <name>privateboard.date.label</name>
        <value>Abierta : </value>
    </element>
    <element>
        <name>privateboard.subject.label</name>
        <value>Tema : </value>
    </element>
    <element>
        <name>privateboard.message.label</name>
        <value>Mensaje : </value>
    </element>
    <element>
        <name>privateboard.send.link</name>
        <value>Enviar</value>
    </element>
    <element>
        <name>privateboard.send.label</name>
        <value> sólo a : </value>
    </element>
    <element>
        <name>privateboard.close.label</name>
        <value>cerrar esta ventana</value>
    </element>
    <element>
        <name>privateboard.comment.label</name>
        <value>Los mensajes enviados desde esta ventana son privados.</value>
    </element>
    <!-- Resources commands -->
    <element>
        <name>user.command.time.format</name>
        <value>dd/MM/yyyy HH:mm:ss</value>
    </element>
    <element>
        <name>user.command.time.help</name>
        <value>Vuelve hora del servidor</value>
    </element>
    <element>
        <name>user.command.chat.help</name>
        <value>Enviar mensaje privado</value>
    </element>
    <element>
        <name>user.command.refresh.help</name>
        <value>Actualizar mensajes</value>
    </element>
    <element>
        <name>user.command.quit.help</name>
        <value>Salir de la sala de chat</value>
    </element>
    <element>
        <name>user.command.logout.help</name>
        <value>Salir del chat</value>
    </element>
    <element>
        <name>moderator.command.generatetranscript.help</name>
        <value>Transcribir en archivo</value>
    </element>
    <element>
        <name>moderator.command.openchatroom.help</name>
        <value>Abrir nueva sala de chat</value>
    </element>
    <element>
        <name>moderator.command.clearchatroom.help</name>
        <value>Borrar sala de chat</value>
    </element>
    <element>
        <name>moderator.command.closechatroom.help</name>
        <value>Cerrar sala de chat</value>
    </element>
    <element>
        <name>moderator.command.kickoff.help</name>
        <value>Expulsar el usuario</value>
    </element>
    <element>
        <name>moderator.command.ban.help</name>
        <value>Restringir el acceso a un usuario</value>
    </element>
    <element>
        <name>moderator.command.clear.help</name>
        <value>Borrar lista negra</value>
    </element>
    <element>
        <name>system.command.backup.help</name>
        <value>Respaldar salas de chat</value>
    </element>
    <element>
        <name>system.command.addmoderator.help</name>
        <value>Nuevo asesor</value>
    </element>
    <element>
        <name>system.command.updatemoderator.help</name>
        <value>Actualizar el asesor</value>
    </element>
    <element>
        <name>system.command.removemoderator.help</name>
        <value>Remover el asesor</value>
    </element>
    <element>
        <name>system.command.updatesystem.help</name>
        <value>Actualizar configuración del sistema</value>
    </element>
    <!-- Global resources -->
    <element>
        <name>global.encoding</name>
        <value>iso-8859-1</value>
    </element>
</resources>

=== rkproject24/virtual-classroom/source/WebContent/WEB-INF/conf/resources_da.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE resources SYSTEM "jchatboxresources.dtd"> -->
<resources>
    <!-- Resources matching to login.jsp -->
    <element>
        <name>login.date.format</name>
        <value>yyyy/MM/dd HH:mm</value>
    </element>
    <element>
        <name>login.title</name>
        <value>Chat Login</value>
    </element>
    <element>
        <name>login.username.label</name>
        <value>Chatnavn : </value>
    </element>
    <element>
        <name>login.join.link</name>
        <value>Indtast</value>
    </element>
    <element>
        <name>login.join.label</name>
        <value> Chatrum : </value>
    </element>
    <element>
        <name>login.list.label</name>
        <value>Vælg et chatrum</value>
    </element>
    <element>
        <name>login.chatroom.label</name>
        <value>Chatrum : </value>
    </element>
    <element>
        <name>login.open.label</name>
        <value>Åben : </value>
    </element>
    <element>
        <name>login.subject.label</name>
        <value>Emne : </value>
    </element>
    <element>
        <name>login.useramount.label</name>
        <value>Tilsluttede brugere : </value>
    </element>
    <element>
        <name>login.userlimit.label</name>
        <value>Tilladte brugere : </value>
    </element>
    <element>
        <name>login.chatroomnotfound.error</name>
        <value>CHATRUM IKKE FUNDET.</value>
    </element>
    <element>
        <name>login.closed.error</name>
        <value>CHATRUM ER LUKKET.</value>
    </element>
    <element>
        <name>login.novacancies.error</name>
        <value>IKKE PLADS PÅ CHATRUM.</value>
    </element>
    <element>
        <name>login.namenotavailable.error</name>
        <value>NAVNET ER IKKE LEDIGT.</value>
    </element>
    <element>
        <name>login.banned.error</name>
        <value>DU ER BORTVIST.</value>
    </element>
    <!-- Resources matching to chatroom.jsp -->
    <element>
        <name>chatroom.date.format</name>
        <value>yyyy/MM/dd HH:mm</value>
    </element>
    <element>
        <name>chatroom.title</name>
        <value>Chat indhold</value>
    </element>
    <element>
        <name>chatroom.join.label</name>
        <value> er med i chatten.</value>
    </element>
    <element>
        <name>chatroom.quit.label</name>
        <value> har forladt chatten.</value>
    </element>
    <element>
        <name>chatroom.userlist.label</name>
        <value>Brugere : </value>
    </element>
    <!-- Resources matching to text.jsp -->
    <element>
        <name>board.date.format</name>
        <value>yyyy/MM/dd HH:mm</value>
    </element>
    <element>
        <name>board.title</name>
        <value>Chat Opslagstavle</value>
    </element>
    <element>
        <name>board.chatroom.label</name>
        <value>Chatrum : </value>
    </element>
    <element>
        <name>board.date.label</name>
        <value>Åben siden : </value>
    </element>
    <element>
        <name>board.subject.label</name>
        <value>Emne : </value>
    </element>
    <element>
        <name>board.message.label</name>
        <value>Besked : </value>
    </element>
    <element>
        <name>board.send.link</name>
        <value>Send</value>
    </element>
    <element>
        <name>board.send.label</name>
        <value> til alle brugere</value>
    </element>
    <element>
        <name>board.refresh.link</name>
        <value>opdater</value>
    </element>
    <element>
        <name>board.logout.link</name>
        <value>log af</value>
    </element>
    <!-- Resources matching to private.jsp -->
    <element>
        <name>privateboard.date.format</name>
        <value>yyyy/MM/dd</value>
    </element>
    <element>
        <name>privateboard.title</name>
        <value>Privat Chatopslagstavle</value>
    </element>
    <element>
        <name>privateboard.chatroom.label</name>
        <value>Chatrum : </value>
    </element>
    <element>
        <name>privateboard.date.label</name>
        <value>Åben siden : </value>
    </element>
    <element>
        <name>privateboard.subject.label</name>
        <value>Emne : </value>
    </element>
    <element>
        <name>privateboard.message.label</name>
        <value>Besked : </value>
    </element>
    <element>
        <name>privateboard.send.link</name>
        <value>Send</value>
    </element>
    <element>
        <name>privateboard.send.label</name>
        <value> til : </value>
    </element>
    <element>
        <name>privateboard.close.label</name>
        <value>luk dette vindue</value>
    </element>
    <element>
        <name>privateboard.comment.label</name>
        <value>Beskeder sendt fra dette vindue er private.</value>
    </element>
    <!-- Resources commands -->
    <element>
        <name>user.command.time.format</name>
        <value>yyyy/MM/dd HH:mm:ss</value>
    </element>
    <element>
        <name>user.command.time.help</name>
        <value>Angiver server tid</value>
    </element>
    <element>
        <name>user.command.chat.help</name>
        <value>Sender privatbesked til modtageren</value>
    </element>
    <element>
        <name>user.command.refresh.help</name>
        <value>Genopfrisker chatrummets indhold</value>
    </element>
    <element>
        <name>user.command.quit.help</name>
        <value>Forlader nuværende chatrum</value>
    </element>
    <element>
        <name>user.command.logout.help</name>
        <value>Forlader det nuværende chatrum</value>
    </element>
    <element>
        <name>moderator.command.generatetranscript.help</name>
        <value>Kopier nuværende chatrums indhold til fil</value>
    </element>
    <element>
        <name>moderator.command.openchatroom.help</name>
        <value>Åbner et nyt chatrum</value>
    </element>
    <element>
        <name>moderator.command.clearchatroom.help</name>
        <value>Renser det nuværende chatrum</value>
    </element>
    <element>
        <name>moderator.command.closechatroom.help</name>
        <value>Lukker det nuværende chatrum</value>
    </element>
    <element>
        <name>moderator.command.kickoff.help</name>
        <value>Bortviser brugernavn fra chatrummet</value>
    </element>
    <element>
        <name>moderator.command.ban.help</name>
        <value>Banlyser brugernavn fra chatrummet</value>
    </element>
    <element>
        <name>moderator.command.clear.help</name>
        <value>Ophæver nuværende chatrums sorte liste</value>
    </element>
    <element>
        <name>system.command.backup.help</name>
        <value>Sikkerhedskopirer alle chatrumene</value>
    </element>
    <element>
        <name>system.command.addmoderator.help</name>
        <value>Tilføjer ny moderator</value>
    </element>
    <element>
        <name>system.command.updatemoderator.help</name>
        <value>Opdaterer en moderator</value>
    </element>
    <element>
        <name>system.command.removemoderator.help</name>
        <value>Fjerner en moderator</value>
    </element>
    <element>
        <name>system.command.updatesystem.help</name>
        <value>Opdaterer system parametre</value>
    </element>
    <!-- Global resources -->
    <element>
        <name>global.encoding</name>
        <value>iso-8859-1</value>
    </element>
</resources>

=== rkproject24/virtual-classroom/trunk/source/WebContent/WEB-INF/conf/resources_en.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE resources SYSTEM "jchatboxresources.dtd">  -->
<resources>
    <!-- Resources matching to login.jsp -->
    <element>
        <name>login.date.format</name>
        <value>yyyy/MM/dd HH:mm</value>
    </element>
    <element>
        <name>login.title</name>
        <value>Chat Login</value>
    </element>
    <element>
        <name>login.username.label</name>
        <value>NickName : </value>
    </element>
    <element>
        <name>login.join.link</name>
        <value>Enter</value>
    </element>
    <element>
        <name>login.join.label</name>
        <value> chatroom : </value>
    </element>
    <element>
        <name>login.list.label</name>
        <value>Select a chatroom</value>
    </element>
    <element>
        <name>login.chatroom.label</name>
        <value>Chatroom : </value>
    </element>
    <element>
        <name>login.open.label</name>
        <value>Opened : </value>
    </element>
    <element>
        <name>login.subject.label</name>
        <value>Subject : </value>
    </element>
    <element>
        <name>login.useramount.label</name>
        <value>Connected users : </value>
    </element>
    <element>
        <name>login.userlimit.label</name>
        <value>Users allowed : </value>
    </element>
    <element>
        <name>login.chatroomnotfound.error</name>
        <value>CHATROOM NOT FOUND.</value>
    </element>
    <element>
        <name>login.closed.error</name>
        <value>CHATROOM IS CLOSED.</value>
    </element>
    <element>
        <name>login.novacancies.error</name>
        <value>CHATROOM IS FULL.</value>
    </element>
    <element>
        <name>login.namenotavailable.error</name>
        <value>NAME NOT AVAILABLE.</value>
    </element>
    <element>
        <name>login.banned.error</name>
        <value>YOU'RE BANNED.</value>
    </element>
    <!-- Resources matching to chatroom.jsp -->
    <element>
        <name>chatroom.date.format</name>
        <value>yyyy/MM/dd HH:mm</value>
    </element>
    <element>
        <name>chatroom.title</name>
        <value>Chat Content</value>
    </element>
    <element>
        <name>chatroom.join.label</name>
        <value> has joined chatroom.</value>
    </element>
    <element>
        <name>chatroom.quit.label</name>
        <value> has left chatroom.</value>
    </element>
    <element>
        <name>chatroom.userlist.label</name>
        <value>Users : </value>
    </element>
    <!-- Resources matching to text.jsp -->
    <element>
        <name>board.date.format</name>
        <value>yyyy/MM/dd HH:mm</value>
    </element>
    <element>
        <name>board.title</name>
        <value>Chat Board</value>
    </element>
    <element>
        <name>board.chatroom.label</name>
        <value>Chatroom : </value>
    </element>
    <element>
        <name>board.date.label</name>
        <value>Opened since : </value>
    </element>
    <element>
        <name>board.subject.label</name>
        <value>Subject : </value>
    </element>
    <element>
        <name>board.message.label</name>
        <value>Message : </value>
    </element>
    <element>
        <name>board.send.link</name>
        <value>Send</value>
    </element>
    <element>
        <name>board.send.label</name>
        <value> to All Users</value>
    </element>
    <element>
        <name>board.refresh.link</name>
        <value>refresh</value>
    </element>
    <element>
        <name>board.logout.link</name>
        <value>Leave Chat Room</value>
    </element>
    <!-- Resources matching to private.jsp -->
    <element>
        <name>privateboard.date.format</name>
        <value>yyyy/MM/dd</value>
    </element>
    <element>
        <name>privateboard.title</name>
        <value>Private Chat Board</value>
    </element>
    <element>
        <name>privateboard.chatroom.label</name>
        <value>Chatroom : </value>
    </element>
    <element>
        <name>privateboard.date.label</name>
        <value>Opened since : </value>
    </element>
    <element>
        <name>privateboard.subject.label</name>
        <value>Subject : </value>
    </element>
    <element>
        <name>privateboard.message.label</name>
        <value>Message : </value>
    </element>
    <element>
        <name>privateboard.send.link</name>
        <value>Send</value>
    </element>
    <element>
        <name>privateboard.send.label</name>
        <value> to : </value>
    </element>
    <element>
        <name>privateboard.close.label</name>
        <value>close this window</value>
    </element>
    <element>
        <name>privateboard.comment.label</name>
        <value>Messages sent from this window are private.</value>
    </element>
    <!-- Resources commands -->
    <element>
        <name>user.command.time.format</name>
        <value>yyyy/MM/dd HH:mm:ss</value>
    </element>
    <element>
        <name>user.command.time.help</name>
        <value>Returns server time</value>
    </element>
    <element>
        <name>user.command.chat.help</name>
        <value>Sends message to recipient</value>
    </element>
    <element>
        <name>user.command.refresh.help</name>
        <value>Refreshes chatroom's content</value>
    </element>
    <element>
        <name>user.command.quit.help</name>
        <value>Leaves the current chatroom</value>
    </element>
    <element>
        <name>user.command.logout.help</name>
        <value>Exits the current chatroom</value>
    </element>
    <element>
        <name>moderator.command.generatetranscript.help</name>
        <value>Dumps current room content to file</value>
    </element>
    <element>
        <name>moderator.command.openchatroom.help</name>
        <value>Opens a new chatroom</value>
    </element>
    <element>
        <name>moderator.command.clearchatroom.help</name>
        <value>Cleans the current chatroom</value>
    </element>
    <element>
        <name>moderator.command.closechatroom.help</name>
        <value>Closes the current chatroom</value>
    </element>
    <element>
        <name>moderator.command.kickoff.help</name>
        <value>Kicks off username from chatroom</value>
    </element>
    <element>
        <name>moderator.command.ban.help</name>
        <value>Bans username from chatroom</value>
    </element>
    <element>
        <name>moderator.command.clear.help</name>
        <value>Clears blacklist of the current chatroom</value>
    </element>
    <element>
        <name>system.command.backup.help</name>
        <value>Backups all chatrooms</value>
    </element>
    <element>
        <name>system.command.addmoderator.help</name>
        <value>Adds a new moderator</value>
    </element>
    <element>
        <name>system.command.updatemoderator.help</name>
        <value>Updates a moderator</value>
    </element>
    <element>
        <name>system.command.removemoderator.help</name>
        <value>Removes a moderator</value>
    </element>
    <element>
        <name>system.command.updatesystem.help</name>
        <value>Updates system parameters</value>
    </element>
    <!-- Global resources -->
    <element>
        <name>global.encoding</name>
        <value>iso-8859-1</value>
    </element>
</resources>
