=== rkproject24/virtual-classroom/tags/8Jan2012/WebContent/WEB-INF/conf/jchatboxresources.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- jChaBox resource DTD - JavaZOOM -->
<!ELEMENT resources (element*)>
<!--Resource's element-->
<!ELEMENT element (name, value)>
<!--Resource's name-->
<!ELEMENT name (#PCDATA)>
<!--Resource's value-->
<!ELEMENT value (#PCDATA)>

=== rkproject24/virtual-classroom/tags/8Jan2012/WebContent/WEB-INF/conf/resources_pt.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE resources SYSTEM "jchatboxresources.dtd">  -->
<resources>
    <!-- Resources matching to login.jsp -->
    <element>
        <name>login.date.format</name>
        <value>dd/MM/yyyy HH:mm</value>
    </element>
    <element>
        <name>login.title</name>
        <value>Login do Chat</value>
    </element>
    <element>
        <name>login.username.label</name>
        <value>Apelido : </value>
    </element>
    <element>
        <name>login.join.link</name>
        <value>Entre</value>
    </element>
    <element>
        <name>login.join.label</name>
        <value> sala de chat : </value>
    </element>
    <element>
        <name>login.list.label</name>
        <value>Selecione uma sala de chat</value>
    </element>
    <element>
        <name>login.chatroom.label</name>
        <value>Sala de Chat : </value>
    </element>
    <element>
        <name>login.open.label</name>
        <value>Aberto : </value>
    </element>
    <element>
        <name>login.subject.label</name>
        <value>Assunto : </value>
    </element>
    <element>
        <name>login.useramount.label</name>
        <value>Usuários Conectados : </value>
    </element>
    <element>
        <name>login.userlimit.label</name>
        <value>Usuários Permitidos : </value>
    </element>
    <element>
        <name>login.chatroomnotfound.error</name>
        <value>SALA DE CHAT NÃO ENCONTRADA.</value>
    </element>
    <element>
        <name>login.closed.error</name>
        <value>SALA DE CHAT ESTÁ FECHADA.</value>
    </element>
    <element>
        <name>login.novacancies.error</name>
        <value>SALA DE CHAT ESTÁ CHEIA.</value>
    </element>
    <element>
        <name>login.namenotavailable.error</name>
        <value>NOME NÃO DISPONÍVEL.</value>
    </element>
    <element>
        <name>login.banned.error</name>
        <value>VOCÊ ESTÁ BANIDO.</value>
    </element>
    <!-- Resources matching to chatroom.jsp -->
    <element>
        <name>chatroom.date.format</name>
        <value>dd/MM/yyyy HH:mm</value>
    </element>
    <element>
        <name>chatroom.title</name>
        <value>Conteúdo do Chat</value>
    </element>
    <element>
        <name>chatroom.join.label</name>
        <value> entrou na sala de chat.</value>
    </element>
    <element>
        <name>chatroom.quit.label</name>
        <value> deixou a sala de chat.</value>
    </element>
    <element>
        <name>chatroom.userlist.label</name>
        <value>Usuários : </value>
    </element>
    <!-- Resources matching to text.jsp -->
    <element>
        <name>board.date.format</name>
        <value>dd/MM/yyyy HH:mm</value>
    </element>
    <element>
        <name>board.title</name>
        <value>Área de Chat</value>
    </element>
    <element>
        <name>board.chatroom.label</name>
        <value>Sala de Chat : </value>
    </element>
    <element>
        <name>board.date.label</name>
        <value>Aberto desde : </value>
    </element>
    <element>
        <name>board.subject.label</name>
        <value>Assunto : </value>
    </element>
    <element>
        <name>board.message.label</name>
        <value>Mensagem : </value>
    </element>
    <element>
        <name>board.send.link</name>
        <value>Enviar</value>
    </element>
    <element>
        <name>board.send.label</name>
        <value> a todos os Usuários</value>
    </element>
    <element>
        <name>board.refresh.link</name>
        <value>atualizar</value>
    </element>
    <element>
        <name>board.logout.link</name>
        <value>sair</value>
    </element>
    <!-- Resources matching to private.jsp -->
    <element>
        <name>privateboard.date.format</name>
        <value>dd/MM/yyyy</value>
    </element>
    <element>
        <name>privateboard.title</name>
        <value>Área de Chat Privada</value>
    </element>
    <element>
        <name>privateboard.chatroom.label</name>
        <value>Sala de Chat : </value>
    </element>
    <element>
        <name>privateboard.date.label</name>
        <value>Aberto desde : </value>
    </element>
    <element>
        <name>privateboard.subject.label</name>
        <value>Assunto : </value>
    </element>
    <element>
        <name>privateboard.message.label</name>
        <value>Mensagem : </value>
    </element>
    <element>
        <name>privateboard.send.link</name>
        <value>Enviar</value>
    </element>
    <element>
        <name>privateboard.send.label</name>
        <value> para : </value>
    </element>
    <element>
        <name>privateboard.close.label</name>
        <value>fechar esta janela</value>
    </element>
    <element>
        <name>privateboard.comment.label</name>
        <value>Mensagens enviadas desta janela são privadas.</value>
    </element>
    <!-- Resources commands -->
    <element>
        <name>user.command.time.format</name>
        <value>dd/MM/yyyy HH:mm:ss</value>
    </element>
    <element>
        <name>user.command.time.help</name>
        <value>Retorna hora do servidor</value>
    </element>
    <element>
        <name>user.command.chat.help</name>
        <value>Envia mensagem ao remetente</value>
    </element>
    <element>
        <name>user.command.refresh.help</name>
        <value>Atualiza conteúdo das salas de chat</value>
    </element>
    <element>
        <name>user.command.quit.help</name>
        <value>Deixa a sala de chat atual</value>
    </element>
    <element>
        <name>user.command.logout.help</name>
        <value>Sai da sala de chat atual</value>
    </element>
    <element>
        <name>moderator.command.generatetranscript.help</name>
        <value>Grava conteúdo da sala de chat atual em arquivo</value>
    </element>
    <element>
        <name>moderator.command.openchatroom.help</name>
        <value>Abre uma nova sala de chat</value>
    </element>
    <element>
        <name>moderator.command.clearchatroom.help</name>
        <value>Limpa a sala de chat atual</value>
    </element>
    <element>
        <name>moderator.command.closechatroom.help</name>
        <value>Fecha a sala de chat atual</value>
    </element>
    <element>
        <name>moderator.command.kickoff.help</name>
        <value>Remove nome de usuário do chat</value>
    </element>
    <element>
        <name>moderator.command.ban.help</name>
        <value>Bane nome de usuário da sala de chat</value>
    </element>
    <element>
        <name>moderator.command.clear.help</name>
        <value>Limpa a lista negra da sala de chat atual</value>
    </element>
    <element>
        <name>system.command.backup.help</name>
        <value>Faz o backup de todas as salas de chat</value>
    </element>
    <element>
        <name>system.command.addmoderator.help</name>
        <value>Adiciona um novo moderador</value>
    </element>
    <element>
        <name>system.command.updatemoderator.help</name>
        <value>Atualiza um moderador</value>
    </element>
    <element>
        <name>system.command.removemoderator.help</name>
        <value>Remove um moderador</value>
    </element>
    <element>
        <name>system.command.updatesystem.help</name>
        <value>Atualiza os parâmetros do sistema</value>
    </element>
    <!-- Global resources -->
    <element>
        <name>global.encoding</name>
        <value>iso-8859-1</value>
    </element>
</resources>

=== rkproject24/virtual-classroom/tags/8Jan2012/WebContent/WEB-INF/conf/resources_fr.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE resources SYSTEM "jchatboxresources.dtd"> -->
<resources>
    <!-- Resources matching to login.jsp -->
    <element>
        <name>login.date.format</name>
        <value>dd/MM/yyyy HH:mm</value>
    </element>
    <element>
        <name>login.title</name>
        <value>Page d'accueil</value>
    </element>
    <element>
        <name>login.username.label</name>
        <value>Pseudonyme : </value>
    </element>
    <element>
        <name>login.join.link</name>
        <value>Entrer</value>
    </element>
    <element>
        <name>login.join.label</name>
        <value> dans la salle : </value>
    </element>
    <element>
        <name>login.list.label</name>
        <value>Sélectionnez une salle</value>
    </element>
    <element>
        <name>login.chatroom.label</name>
        <value>Salle : </value>
    </element>
    <element>
        <name>login.open.label</name>
        <value>Ouverte depuis le : </value>
    </element>
    <element>
        <name>login.subject.label</name>
        <value>Sujet : </value>
    </element>
    <element>
        <name>login.useramount.label</name>
        <value>Utilisateurs connectés : </value>
    </element>
    <element>
        <name>login.userlimit.label</name>
        <value>Nombre maximum d'utilisateurs : </value>
    </element>
    <element>
        <name>login.chatroomnotfound.error</name>
        <value>SALLE INCONNUE.</value>
    </element>
    <element>
        <name>login.closed.error</name>
        <value>SALLE FERMEE.</value>
    </element>
    <element>
        <name>login.novacancies.error</name>
        <value>SALLE COMPLETE.</value>
    </element>
    <element>
        <name>login.namenotavailable.error</name>
        <value>PSEUDONYME DEJA PRIS.</value>
    </element>
    <element>
        <name>login.banned.error</name>
        <value>VOUS ETES EXCLU DE CETTE SALLE.</value>
    </element>
    <!-- Resources matching to chatroom.jsp -->
    <element>
        <name>chatroom.date.format</name>
        <value>HH:mm:ss</value>
    </element>
    <element>
        <name>chatroom.title</name>
        <value>Salle</value>
    </element>
    <element>
        <name>chatroom.join.label</name>
        <value> a rejoint cette salle.</value>
    </element>
    <element>
        <name>chatroom.quit.label</name>
        <value> a quitté cette salle.</value>
    </element>
    <element>
        <name>chatroom.userlist.label</name>
        <value>Membres : </value>
    </element>
    <!-- Resources matching to text.jsp -->
    <element>
        <name>board.date.format</name>
        <value>dd/MM/yyyy HH:mm</value>
    </element>
    <element>
        <name>board.title</name>
        <value>Controles</value>
    </element>
    <element>
        <name>board.chatroom.label</name>
        <value>Salle : </value>
    </element>
    <element>
        <name>board.date.label</name>
        <value>Ouverte depuis : </value>
    </element>
    <element>
        <name>board.subject.label</name>
        <value>Sujet : </value>
    </element>
    <element>
        <name>board.message.label</name>
        <value>Message : </value>
    </element>
    <element>
        <name>board.send.link</name>
        <value>Envoyer</value>
    </element>
    <element>
        <name>board.send.label</name>
        <value> à tous les utilisateurs</value>
    </element>
    <element>
        <name>board.refresh.link</name>
        <value>Rafraîchir</value>
    </element>
    <element>
        <name>board.logout.link</name>
        <value>Quitter</value>
    </element>
    <!-- Resources matching to private.jsp -->
    <element>
        <name>privateboard.date.format</name>
        <value>dd/MM/yyyy</value>
    </element>
    <element>
        <name>privateboard.title</name>
        <value>Messages privés</value>
    </element>
    <element>
        <name>privateboard.chatroom.label</name>
        <value>Salle : </value>
    </element>
    <element>
        <name>privateboard.date.label</name>
        <value>Ouverte depuis : </value>
    </element>
    <element>
        <name>privateboard.subject.label</name>
        <value>Sujet : </value>
    </element>
    <element>
        <name>privateboard.message.label</name>
        <value>Message : </value>
    </element>
    <element>
        <name>privateboard.send.link</name>
        <value>Envoyer</value>
    </element>
    <element>
        <name>privateboard.send.label</name>
        <value> à : </value>
    </element>
    <element>
        <name>privateboard.close.label</name>
        <value>Fermer cette fenêtre</value>
    </element>
    <element>
        <name>privateboard.comment.label</name>
        <value>Les messages envoyés depuis cette fenêtre sont privés.</value>
    </element>
    <!-- Resources commands -->
    <element>
        <name>user.command.time.format</name>
        <value>dd/MM/yyyy HH:mm:ss</value>
    </element>
    <element>
        <name>user.command.time.help</name>
        <value>Affiche la date et l'heure du serveur</value>
    </element>
    <element>
        <name>user.command.chat.help</name>
        <value>Envoie un message à un utilisateur</value>
    </element>
    <element>
        <name>user.command.refresh.help</name>
        <value>Rafraîchit le contenu de la salle</value>
    </element>
    <element>
        <name>user.command.quit.help</name>
        <value>Quitter la salle</value>
    </element>
    <element>
        <name>user.command.logout.help</name>
        <value>Sortir de la salle</value>
    </element>
    <element>
        <name>moderator.command.generatetranscript.help</name>
        <value>Enregistre le contenu de la salle dans un fichier</value>
    </element>
    <element>
        <name>moderator.command.openchatroom.help</name>
        <value>Ouvre une nouvelle salle</value>
    </element>
    <element>
        <name>moderator.command.clearchatroom.help</name>
        <value>Vide le contenu de la salle</value>
    </element>
    <element>
        <name>moderator.command.closechatroom.help</name>
        <value>Ferme la salle</value>
    </element>
    <element>
        <name>moderator.command.kickoff.help</name>
        <value>Ejecte un utilisateur de la salle</value>
    </element>
    <element>
        <name>moderator.command.ban.help</name>
        <value>Banit un utilisateur de la salle</value>
    </element>
    <element>
        <name>moderator.command.clear.help</name>
        <value>Efface le contenu de la liste noire</value>
    </element>
    <element>
        <name>system.command.backup.help</name>
        <value>Sauvegarde toutes les salles</value>
    </element>
    <element>
        <name>system.command.addmoderator.help</name>
        <value>Ajoute un nouveau modérateur</value>
    </element>
    <element>
        <name>system.command.updatemoderator.help</name>
        <value>Met à jour un modérateur</value>
    </element>
    <element>
        <name>system.command.removemoderator.help</name>
        <value>Supprime un modérateur</value>
    </element>
    <element>
        <name>system.command.updatesystem.help</name>
        <value>Mets à jour les paramètres système</value>
    </element>
    <!-- Global resources -->
    <element>
        <name>global.encoding</name>
        <value>iso-8859-1</value>
    </element>
</resources>

=== rkproject24/virtual-classroom/trunk/source/WebContent/WEB-INF/conf/resources_de.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE resources SYSTEM "jchatboxresources.dtd">  -->
<resources>
    <!-- Resources matching to login.jsp -->
    <element>
        <name>login.date.format</name>
        <value>yyyy/MM/dd HH:mm</value>
    </element>
    <element>
        <name>login.title</name>
        <value>Chat Login</value>
    </element>
    <element>
        <name>login.username.label</name>
        <value>Benutzername : </value>
    </element>
    <element>
        <name>login.join.link</name>
        <value>Eintreten</value>
    </element>
    <element>
        <name>login.join.label</name>
        <value> Chatroom : </value>
    </element>
    <element>
        <name>login.list.label</name>
        <value>Wähle einen Chatroom</value>
    </element>
    <element>
        <name>login.chatroom.label</name>
        <value>Chatroom : </value>
    </element>
    <element>
        <name>login.open.label</name>
        <value>Geöffnet : </value>
    </element>
    <element>
        <name>login.subject.label</name>
        <value>Thema : </value>
    </element>
    <element>
        <name>login.useramount.label</name>
        <value>Verbundene Benutzer : </value>
    </element>
    <element>
        <name>login.userlimit.label</name>
        <value>Max. erlaubte Benutzer : </value>
    </element>
    <element>
        <name>login.chatroomnotfound.error</name>
        <value>CHATROOM NICHT GEFUNDEN.</value>
    </element>
    <element>
        <name>login.closed.error</name>
        <value>CHATROOM IST GESCHLOSSEN.</value>
    </element>
    <element>
        <name>login.novacancies.error</name>
        <value>CHATROOM IST VOLL.</value>
    </element>
    <element>
        <name>login.namenotavailable.error</name>
        <value>BENUTZERNAME SCHON IN BENUTZUNG.</value>
    </element>
    <element>
        <name>login.banned.error</name>
        <value>DU WURDEST VERBANNT.</value>
    </element>
    <!-- Resources matching to chatroom.jsp -->
    <element>
        <name>chatroom.date.format</name>
        <value>yyyy/MM/dd HH:mm</value>
    </element>
    <element>
        <name>chatroom.title</name>
        <value>Chat Thema</value>
    </element>
    <element>
        <name>chatroom.join.label</name>
        <value> hat den raum betreten.</value>
    </element>
    <element>
        <name>chatroom.quit.label</name>
        <value> hat den raum verlassen.</value>
    </element>
    <element>
        <name>chatroom.userlist.label</name>
        <value>Benutzer : </value>
    </element>
    <!-- Resources matching to text.jsp -->
    <element>
        <name>board.date.format</name>
        <value>yyyy/MM/dd HH:mm</value>
    </element>
    <element>
        <name>board.title</name>
        <value>Chat Board</value>
    </element>
    <element>
        <name>board.chatroom.label</name>
        <value>Chatroom : </value>
    </element>
    <element>
        <name>board.date.label</name>
        <value>Geöffnet seit : </value>
    </element>
    <element>
        <name>board.subject.label</name>
        <value>Thema : </value>
    </element>
    <element>
        <name>board.message.label</name>
        <value>Nachricht : </value>
    </element>
    <element>
        <name>board.send.link</name>
        <value>Senden</value>
    </element>
    <element>
        <name>board.send.label</name>
        <value> An alle Benutzer</value>
    </element>
    <element>
        <name>board.refresh.link</name>
        <value>aktualisieren</value>
    </element>
    <element>
        <name>board.logout.link</name>
        <value>abmelden</value>
    </element>
    <!-- Resources matching to private.jsp -->
    <element>
        <name>privateboard.date.format</name>
        <value>yyyy/MM/dd</value>
    </element>
    <element>
        <name>privateboard.title</name>
        <value>Privates Chat Board</value>
    </element>
    <element>
        <name>privateboard.chatroom.label</name>
        <value>Chatroom : </value>
    </element>
    <element>
        <name>privateboard.date.label</name>
        <value>Geöffnet seit : </value>
    </element>
    <element>
        <name>privateboard.subject.label</name>
        <value>Thema : </value>
    </element>
    <element>
        <name>privateboard.message.label</name>
        <value>Nachricht : </value>
    </element>
    <element>
        <name>privateboard.send.link</name>
        <value>Senden</value>
    </element>
    <element>
        <name>privateboard.send.label</name>
        <value> an : </value>
    </element>
    <element>
        <name>privateboard.close.label</name>
        <value>dieses Fenster schließen</value>
    </element>
    <element>
        <name>privateboard.comment.label</name>
        <value>Nachrichten die von diesem Fenster gesendet werden sind privat.</value>
    </element>
    <!-- Resources commands -->
    <element>
        <name>user.command.time.format</name>
        <value>yyyy/MM/dd HH:mm</value>
    </element>
    <element>
        <name>user.command.time.help</name>
        <value>Gibt die Serverzeit an</value>
    </element>
    <element>
        <name>user.command.chat.help</name>
        <value>Sendet eine Nachricht an den Empfänger</value>
    </element>
    <element>
        <name>user.command.refresh.help</name>
        <value>Aktualisiert den Inhalt des Chatrooms</value>
    </element>
    <element>
        <name>user.command.quit.help</name>
        <value>Den Chatraum verlassen</value>
    </element>
    <element>
        <name>user.command.logout.help</name>
        <value>Aus dem aktuellen Chatroom abmelden</value>
    </element>
    <element>
        <name>moderator.command.generatetranscript.help</name>
        <value>Speichert den Chatroominhalt in eine Datei</value>
    </element>
    <element>
        <name>moderator.command.openchatroom.help</name>
        <value>Erstellt einen neuen Chatroom</value>
    </element>
    <element>
        <name>moderator.command.clearchatroom.help</name>
        <value>Löscht den Inhalt des Chatrooms</value>
    </element>
    <element>
        <name>moderator.command.closechatroom.help</name>
        <value>Schließt den Chatroom</value>
    </element>
    <element>
        <name>moderator.command.kickoff.help</name>
        <value>Benutzer aus dem Chatroom entfernen</value>
    </element>
    <element>
        <name>moderator.command.ban.help</name>
        <value>Benutzer aus dem Chatroom verbannen</value>
    </element>
    <element>
        <name>moderator.command.clear.help</name>
        <value>Leert die Schwarze Liste des aktuellen Chatrooms</value>
    </element>
    <element>
        <name>system.command.backup.help</name>
        <value>Erstellt ein Backup aller Chatrooms</value>
    </element>
    <element>
        <name>system.command.addmoderator.help</name>
        <value>Fügt einen Moderator hinzu</value>
    </element>
    <element>
        <name>system.command.updatemoderator.help</name>
        <value>Aktualisiert einen Moderator</value>
    </element>
    <element>
        <name>system.command.removemoderator.help</name>
        <value>Entfernt einen Moderator</value>
    </element>
    <element>
        <name>system.command.updatesystem.help</name>
        <value>Aktualisiert die System Parameters</value>
    </element>
    <!-- Global resources -->
    <element>
        <name>global.encoding</name>
        <value>iso-8859-1</value>
    </element>
</resources>
